image: node:8.12.0
cache:
  key: $CI_PROJECT_NAME
  paths:
    - node_modules/
before_script:
  - node -v
  - yarn -v
stages:
  - test
  - build
  - coverage
  - deploy
unit-test-player:
  stage: test
  script:
    - yarn
    - yarn test
  dependencies: []
build-player:
  stage: build
  script:
    - yarn
    - yarn build
  artifacts:
    paths:
      - build/
  dependencies: []

test-player:
  stage: coverage
  script:
    - yarn
    # update this to `yarn coverage` later
    - yarn test
  dependencies:
    - build-player

deploy-heroku:
  stage: deploy
  script:
    # navigate to artifact folder
    - cd build
    # create static buildpack config
    - 'echo "{\"root\": \"./\"}" > static.json'
    - git config --global user.email "$GIT_CI_EMAIL"
    - git config --global user.name "Gitlab CI"
    # deploy to heroku
    - git init
    - git add .
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git
    - git commit -am "$CI_COMMIT_MESSAGE"
    - git push heroku master --force
  only:
    - master
  dependencies:
    - build-player
