image: node:8.12.0
cache:
  key: ${CI_PROJECT_NAME}
  paths:
    - node_modules/
before_script:
  - node -v
  - yarn -v
stages:
  - test
  - build
  - coverage
  - deploy
unit-test-player:
  stage: test
  script:
    - yarn
    - yarn test
build-player:
  stage: build
  script:
    - yarn
    - yarn build
  artifacts:
    paths:
      - build/

test-player:
  stage: coverage
  script:
    - yarn
    # update this to `yarn coverage` later
    - yarn test

deploy-heroku:
  stage: deploy
  script:
    # install ruby on rails
    - apt-get install -y libgdbm-dev libncurses5-dev automake libtool bison libffi-dev
    - gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
    - curl -sSL https://get.rvm.io | bash -s stable
    - source ~/.rvm/scripts/rvm
    - rvm install 2.5.1
    - rvm use 2.5.1 --default
    - ruby -v
    # install bundler
    - gem install bundler
    # install dpl
    - gem install dpl
    # deploy to heroku
    - dpl --provider=heroku --api-key=$HEROKU_API_KEY --app=$HEROKU_APP
