image: node:8.12.0
cache:
  key: ${CI_PROJECT_NAME}
  paths:
    - node_modules/
before_script:
  - node -v
  - yarn -v
stages:
  - test
  - build
  - coverage
  - deploy
unit-test-player:
  stage: test
  script:
    - yarn
    - yarn test
  dependencies: []
build-player:
  stage: build
  script:
    - yarn
    - yarn build
  artifacts:
    paths:
      - build/
  dependencies: []

test-player:
  stage: coverage
  script:
    - yarn
    # update this to `yarn coverage` later
    - yarn test
  dependencies:
    - build-player

deploy-heroku:
  stage: deploy
  script:
    - yarn global add heroku
    - heroku --version
    - HEROKU_API_KEY=${HEROKU_API_KEY}
    - eroku login
    # navigate to artifact folder
    - cd build
    # deploy to heroku
    - git init
    - heroku git:remote -a ${HEROKU_APP}
    - git add .
    - git commit -am "${CI_COMMIT_MESSAGE}"
    - git push heroku master
  dependencies:
    - build-player
